# Walmart : predict weekly sales

## Company's Description 📇

Walmart Inc. is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores from the United States, headquartered in Bentonville, Arkansas. The company was founded by Sam Walton in 1962.

## Project 🚧

Walmart's marketing service has asked you to build a machine learning model able to estimate the weekly sales in their stores, with the best precision possible on the predictions made. Such a model would help them understand better how the sales are influenced by economic indicators, and might be used to plan future marketing campaigns.

## Goals 🎯

The project can be divided into three steps:

- Part 1 : make an EDA and all the necessary preprocessings to prepare data for machine learning
- Part 2 : train a **linear regression model** (baseline)
- Part 3 : avoid overfitting by training a **regularized regression model**

## Scope of this project 🖼️

For this project, you'll work with a dataset that contains information about weekly sales achieved by different Walmart stores, and other variables such as the unemployment rate or the fuel price, that might be useful for predicting the amount of sales. The dataset has been taken from a Kaggle competition, but we made some changes compared to the original data. Please make sure that you're using **our** custom dataset (available on JULIE). 🤓

## Deliverable 📬

To complete this project, your team should: 

- Create some visualizations
- Train at least one **linear regression model** on the dataset, that predicts the amount of weekly sales as a function of the other variables
- Assess the performances of the model by using a metric that is relevant for regression problems
- Interpret the coefficients of the model to identify what features are important for the prediction
- Train at least one model with **regularization (Lasso or Ridge)** to reduce overfitting

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import r2_score

# EDA and preprocessing

## Raw dataset

In [2]:
# Import du dataset

Walmart = pd.read_csv("./Walmart_Store_sales.csv")
print(Walmart.shape)
display(Walmart.head())
display(Walmart.dtypes)

(150, 8)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,6.0,18-02-2011,1572117.54,NaN,59.61,3.045,214.777523,6.858
1,13.0,25-03-2011,1807545.43,0.0,42.38,3.435,128.616064,7.470
2,17.0,27-07-2012,NaN,0.0,NaN,NaN,130.719581,5.936
3,11.0,NaN,1244390.03,0.0,84.57,NaN,214.556497,7.346
4,6.0,28-05-2010,1644470.66,0.0,78.89,2.759,212.412888,7.092

Store           float64
Date             object
Weekly_Sales    float64
Holiday_Flag    float64
Temperature     float64
Fuel_Price      float64
CPI             float64
Unemployment    float64
dtype: object

In [3]:
# Statistiques basiques sur le dataset original

print("Number of rows : {}".format(Walmart.shape[0]))
print("Number of columns : {}".format(Walmart.shape[1]))

print("\nBasics statistics: ")
display(Walmart.describe(include="all"))

print("\nPercentage of missing values: ")
display(100 * Walmart.isnull().sum() / Walmart.shape[0])

print("\nNumber of duplicated lines: ")
print(Walmart.duplicated().sum())

Number of rows : 150
Number of columns : 8

Basics statistics:

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,150.000000,132,1.360000e+02,138.000000,132.000000,136.000000,138.000000,135.000000
unique,NaN,85,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,19-10-2012,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
mean,9.866667,NaN,1.249536e+06,0.079710,61.398106,3.320853,179.898509,7.598430
std,6.231191,NaN,6.474630e+05,0.271831,18.378901,0.478149,40.274956,1.577173
min,1.000000,NaN,2.689290e+05,0.000000,18.790000,2.514000,126.111903,5.143000
25%,4.000000,NaN,6.050757e+05,0.000000,45.587500,2.852250,131.970831,6.597500
50%,9.000000,NaN,1.261424e+06,0.000000,62.985000,3.451000,197.908893,7.470000
75%,15.750000,NaN,1.806386e+06,0.000000,76.345000,3.706250,214.934616,8.150000
max,20.000000,NaN,2.771397e+06,1.000000,91.650000,4.193000,226.968844,14.313000

Percentage of missing values:

Store            0.000000
Date            12.000000
Weekly_Sales     9.333333
Holiday_Flag     8.000000
Temperature     12.000000
Fuel_Price       9.333333
CPI              8.000000
Unemployment    10.000000
dtype: float64

Number of duplicated lines:
0

Commentaires sur le preprocessing à faire :
1) drop columns
- pas de colonne avec "trop" de valeurs manquantes -> pas de colonne à dropper, sauf la colonne "Date" quand on l'aura remplacée par les colonnes year, month etc. (pour éviter la multicolinéarité)
2) drop rows
- missing values dans le target (Weekly_Sales) : à retirer
- outliers : il ne semble pas y en avoir ailleurs que dans Unemployment, mais à vérifier plus en détail 
3) Imputation 
- il faudra imputer les valeurs manquantes de toutes les colonnes, sauf Store qui n'a pas de NaN
4) Standardisation
- StandardScaler à faire pour toutes les colonnes quantitatives
5) Encoding
- colonne Holiday_Flag est un catégoriel : valeurs 0 ou 1 -> pas besoin de faire du OneHotEncoder
- colonne Store est un catégoriel : de 1 à 20 (avec un peu plus de grandes valeurs que de petites, puisque 2nd quartile à 9 au lieu de 10) -> on va effectuer un OneHotEncoder mais on pourrait envisager de les regrouper en moins de catégories

In [4]:
# Echelle de temps des échantillons

Walmart['Date'] = pd.to_datetime(Walmart["Date"], format = "%d-%m-%Y")
print("date minimale : ", Walmart['Date'].min())
print("date maximale : ", Walmart['Date'].max())

date minimale :  2010-02-05 00:00:00
date maximale :  2012-10-19 00:00:00

In [5]:
# colonne Date : 85 valeurs uniques sur les 132 non-NaN, est-ce une répartition uniforme ?

dict_datesuniques = {}
list_uniques = Walmart['Date'].unique()
list_uniques = list_uniques[~pd.isnull(list_uniques)] # to remove NaN=0
for unique in list_uniques:
    mask = Walmart['Date'] == unique
    dict_datesuniques[unique] = len(Walmart.loc[mask, :])

fig = px.histogram(list(dict_datesuniques.keys()), dict_datesuniques.values(), title="Number of repetitions for all unique dates")
fig.show()

px.bar(x=Walmart['Date'], title="Count of each unique date")

# Conclusion : il n'y a pas de date sur-représentée dans le dataset, on utilisera un KNN pour l'imputation des NaN

## Preprocessing

In [6]:
# drop des lignes sans target

Walmart.dropna(subset=["Weekly_Sales"], inplace=True)

Walmart.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,6.0,2011-02-18,1572117.54,NaN,59.61,3.045,214.777523,6.858
1,13.0,2011-03-25,1807545.43,0.0,42.38,3.435,128.616064,7.470
3,11.0,NaT,1244390.03,0.0,84.57,NaN,214.556497,7.346
4,6.0,2010-05-28,1644470.66,0.0,78.89,2.759,212.412888,7.092
5,4.0,2010-05-28,1857533.70,0.0,NaN,2.756,126.160226,7.896

In [53]:
# définition de la limite des outliers (mean +/- 3 * std) pour les 4 variables quantitatives

data_describe = Walmart.describe(include="all")

col_X_quanti = ["Temperature", "Fuel_Price", "CPI", "Unemployment"]

data_dict = {
    'mean': data_describe.loc["mean",col_X_quanti],
    'std': data_describe.loc["std",col_X_quanti]
}
df_stat = pd.DataFrame(data_dict)
df_stat['outliers_min'] = (df_stat['mean'] - 3*df_stat['std'])
df_stat['outliers_max'] = (df_stat['mean'] + 3*df_stat['std'])
df_stat.head()

                    mean        std outliers_min outliers_max
Temperature    60.853967  18.514432     5.310671   116.397263
Fuel_Price      3.316992    0.47954     1.878371     4.755613
CPI           178.091144  40.243105     57.36183   298.820458
Unemployment    7.665582   1.619428     2.807297    12.523867

In [54]:
# vérification de la présence d'outliers :
# histogrammes des 4 features quantitatives, avec visualisation des limites mean +/- 3 * std

fig = make_subplots(rows = 4, cols = 1)

fig.add_trace(
    go.Histogram(
        x = Walmart["Temperature"], name = "Temperature"),
        row = 1,
        col = 1)
fig.add_shape(
    type="line",
    x0=df_stat.loc["Temperature","outliers_min"],
    y0=0,
    x1=df_stat.loc["Temperature","outliers_min"],
    y1=25,
    xref='x',
    yref="y",
    line=dict(
        color="Red",
        width=2
    ),
    row=1,
    col=1
)
fig.add_shape(
    type="line",
    x0=df_stat.loc["Temperature","outliers_max"],
    y0=0,
    x1=df_stat.loc["Temperature","outliers_max"],
    y1=25,
    xref='x',
    yref="y",
    line=dict(
        color="Red",
        width=2
    ),
    row=1,
    col=1
)

fig.add_trace(
    go.Histogram(
        x = Walmart["Fuel_Price"], name = "Fuel_Price"),
        row = 2,
        col = 1)
fig.add_shape(
    type="line",
    x0=df_stat.loc["Fuel_Price","outliers_min"],
    y0=0,
    x1=df_stat.loc["Fuel_Price","outliers_min"],
    y1=30,
    xref='x',
    yref="y",
    line=dict(
        color="Red",
        width=2
    ),
    row=2,
    col=1
)
fig.add_shape(
    type="line",
    x0=df_stat.loc["Fuel_Price","outliers_max"],
    y0=0,
    x1=df_stat.loc["Fuel_Price","outliers_max"],
    y1=30,
    xref='x',
    yref="y",
    line=dict(
        color="Red",
        width=2
    ),
    row=2,
    col=1
)

fig.add_trace(
    go.Histogram(
        x = Walmart["CPI"], name = "CPI"),
        row = 3,
        col = 1)
fig.add_shape(
    type="line",
    x0=df_stat.loc["CPI","outliers_min"],
    y0=0,
    x1=df_stat.loc["CPI","outliers_min"],
    y1=55,
    xref='x',
    yref="y",
    line=dict(
        color="Red",
        width=2
    ),
    row=3,
    col=1
)
fig.add_shape(
    type="line",
    x0=df_stat.loc["CPI","outliers_max"],
    y0=0,
    x1=df_stat.loc["CPI","outliers_max"],
    y1=55,
    xref='x',
    yref="y",
    line=dict(
        color="Red",
        width=2
    ),
    row=3,
    col=1
)

fig.add_trace(
    go.Histogram(
        x = Walmart["Unemployment"], name = "Unemployment"),
        row = 4,
        col = 1)
fig.add_shape(
    type="line",
    x0=df_stat.loc["Unemployment","outliers_min"],
    y0=0,
    x1=df_stat.loc["Unemployment","outliers_min"],
    y1=22,
    xref='x',
    yref="y",
    line=dict(
        color="Red",
        width=2
    ),
    row=4,
    col=1
)
fig.add_shape(
    type="line",
    x0=df_stat.loc["Unemployment","outliers_max"],
    y0=0,
    x1=df_stat.loc["Unemployment","outliers_max"],
    y1=22,
    xref='x',
    yref="y",
    line=dict(
        color="Red",
        width=2
    ),
    row=4,
    col=1
)

fig.update_layout(width=700, height=1000)

fig.show()

# conclusion : il y a bien des outliers uniquement dans la colonne Unemployement

In [6]:
# vérification des outliers Unemployment

display(Walmart.loc[Walmart['Unemployment'] > 12,:])
display(Walmart.loc[Walmart['Store'] == 12,:])

# Conclusion : on ne peut pas retirer ces 5 outliers, sinon on retire le Store numéro 12 du dataset

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
30,12.0,2011-05-06,1021154.48,0.0,68.40,4.193,129.044433,13.736
62,12.0,2010-12-17,1295605.35,0.0,52.77,3.236,126.879484,14.313
68,12.0,2011-08-12,955913.68,0.0,91.04,3.701,129.201581,13.503
93,12.0,2011-05-27,964332.51,0.0,NaN,4.087,129.062355,13.736
135,12.0,2010-09-10,903119.03,1.0,83.63,3.044,126.114581,14.180

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
30,12.0,2011-05-06,1021154.48,0.0,68.40,4.193,129.044433,13.736
62,12.0,2010-12-17,1295605.35,0.0,52.77,3.236,126.879484,14.313
68,12.0,2011-08-12,955913.68,0.0,91.04,3.701,129.201581,13.503
93,12.0,2011-05-27,964332.51,0.0,NaN,4.087,129.062355,13.736
135,12.0,2010-09-10,903119.03,1.0,83.63,3.044,126.114581,14.180

In [7]:
# Créer les colonnes year, month, day à partir de la colonne Date (qui a des NaN)

Walmart_clean = Walmart.copy(deep=True)
Walmart_clean['year'] = Walmart_clean['Date'].dt.year
Walmart_clean['month'] = Walmart_clean['Date'].dt.month
Walmart_clean['day'] = Walmart_clean['Date'].dt.day
Walmart_clean['weekday'] = Walmart_clean['Date'].dt.weekday
Walmart_clean.drop("Date", axis=1, inplace=True)

print(Walmart_clean['weekday'].value_counts()) 
# les relevés sont toujours faits les vendredis -> on drop la colonne weekday
Walmart_clean = Walmart_clean.drop("weekday", axis=1)

display(Walmart_clean.describe())

weekday
4.0    118
Name: count, dtype: int64

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,year,month,day
count,136.000000,1.360000e+02,125.000000,121.000000,124.000000,125.000000,122.000000,118.000000,118.000000,118.000000
mean,10.014706,1.249536e+06,0.072000,60.853967,3.316992,178.091144,7.665582,2010.822034,6.338983,16.440678
std,6.124614,6.474630e+05,0.259528,18.514432,0.479540,40.243105,1.619428,0.812628,3.173664,8.209378
min,1.000000,2.689290e+05,0.000000,18.790000,2.514000,126.111903,5.143000,2010.000000,1.000000,1.000000
25%,4.000000,6.050757e+05,0.000000,45.220000,2.838500,131.637000,6.690000,2010.000000,4.000000,10.000000
50%,10.000000,1.261424e+06,0.000000,62.250000,3.451000,196.919506,7.477000,2011.000000,6.000000,16.500000
75%,15.250000,1.806386e+06,0.000000,75.950000,3.724000,214.878556,8.150000,2011.750000,9.000000,24.000000
max,20.000000,2.771397e+06,1.000000,91.650000,4.193000,226.968844,14.313000,2012.000000,12.000000,31.000000

## EDA after preprocessing

In [8]:
print("\nPercentage of missing values Walmart: ")
display(100 * Walmart.isnull().sum() / Walmart.shape[0])

print("\nPercentage of missing values Walmart_clean: ")
display(100 * Walmart_clean.isnull().sum() / Walmart_clean.shape[0])

Percentage of missing values Walmart:

Store            0.000000
Date            13.235294
Weekly_Sales     0.000000
Holiday_Flag     8.088235
Temperature     11.029412
Fuel_Price       8.823529
CPI              8.088235
Unemployment    10.294118
dtype: float64

Percentage of missing values Walmart_clean:

Store            0.000000
Weekly_Sales     0.000000
Holiday_Flag     8.088235
Temperature     11.029412
Fuel_Price       8.823529
CPI              8.088235
Unemployment    10.294118
year            13.235294
month           13.235294
day             13.235294
dtype: float64

In [9]:
px.bar(Walmart_clean, x="month", y="Weekly_Sales", facet_col="year", facet_col_wrap=2)

In [10]:
px.histogram(Walmart_clean, "day", color="year", barmode="overlay")

In [12]:
px.histogram(Walmart_clean, "Store", nbins=20)

In [13]:
px.bar(Walmart_clean, x="Store", y="Weekly_Sales")

In [14]:
px.histogram(Walmart_clean, x="Temperature", y="Weekly_Sales")

In [15]:
px.histogram(Walmart_clean, x="Holiday_Flag", y="Weekly_Sales")

In [16]:
px.histogram(Walmart_clean, x="Fuel_Price", y="Weekly_Sales")

In [17]:
px.histogram(Walmart_clean, x="CPI", y="Weekly_Sales")

In [18]:
px.histogram(Walmart_clean, x="Unemployment", y="Weekly_Sales")

In [19]:
fig = px.scatter_matrix(Walmart_clean)
fig.update_layout(
        title = go.layout.Title(text = "Bivariate analysis", x = 0.5), showlegend = False, 
            autosize=False, height=1200, width = 1200)
fig.show()

In [20]:
corr_matrix = Walmart_clean.corr().round(2)

import plotly.figure_factory as ff

fig = ff.create_annotated_heatmap(corr_matrix.values,
                                  x = corr_matrix.columns.tolist(),
                                  y = corr_matrix.index.tolist())


fig.show()

Conclusions : 
- aucune feature ne présente une corrélation de type linéaire avec la target
- les colonnes *quantitatives* qui semblent le plus liées à Weekly_sales sont : CPI, Temperature

## Creation of X and Y datasets

In [21]:
# Separate target variable Y from features X

print("Separating labels from features...")
target_variable = "Weekly_Sales"

X = Walmart_clean.drop(target_variable, axis = 1)
Y = Walmart_clean.loc[:,target_variable]

print("...Done.")
print()

print('Y : ')
print(Y.head())
print()
print('X :')
print(X.head())

Separating labels from features...
...Done.

Y :
0    1572117.54
1    1807545.43
3    1244390.03
4    1644470.66
5    1857533.70
Name: Weekly_Sales, dtype: float64

X :
   Store  Holiday_Flag  Temperature  Fuel_Price         CPI  Unemployment  \
0    6.0           NaN        59.61       3.045  214.777523         6.858
1   13.0           0.0        42.38       3.435  128.616064         7.470
3   11.0           0.0        84.57         NaN  214.556497         7.346
4    6.0           0.0        78.89       2.759  212.412888         7.092
5    4.0           0.0          NaN       2.756  126.160226         7.896

     year  month   day
0  2011.0    2.0  18.0
1  2011.0    3.0  25.0
3     NaN    NaN   NaN
4  2010.0    5.0  28.0
5  2010.0    5.0  28.0

In [22]:
# Divide dataset Train set & Test set 

print("Dividing into train and test sets...")
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print("...Done.")
print()

Dividing into train and test sets...
...Done.

In [23]:
# Define names of numeric/categorical columns

display(X.dtypes)
numeric_features = list(X.columns)
numeric_features.remove('Store')
numeric_features.remove('Holiday_Flag')
categorical_features = ["Store", "Holiday_Flag"]
print("numeric features:", numeric_features)
print("categorical features:", categorical_features)

Store           float64
Holiday_Flag    float64
Temperature     float64
Fuel_Price      float64
CPI             float64
Unemployment    float64
year            float64
month           float64
day             float64
dtype: object

numeric features: ['Temperature', 'Fuel_Price', 'CPI', 'Unemployment', 'year', 'month', 'day']
categorical features: ['Store', 'Holiday_Flag']

In [24]:
# Pipelines to impute missing values, standardize quantitative features and use OHE on missing values

numeric_transformer = Pipeline(
    steps=[
        ("imputer", KNNImputer(n_neighbors=5)),
        ("scaler", StandardScaler()),
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", KNNImputer(n_neighbors=5)), 
        ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ]
)

In [25]:
# Transforming X_train and X_test 

print("Performing preprocessings on train set...")
print(X_train.head())
X_train = preprocessor.fit_transform(X_train)
print("...Done.")
print(
    X_train[0:5]
)  
print()

# Preprocessings on test set
print("Performing preprocessings on test set...")
print(X_test.head())
X_test = preprocessor.transform(X_test)  
print("...Done.")
print(
    X_test[0:5, :]
)  
print()

Performing preprocessings on train set...
     Store  Holiday_Flag  Temperature  Fuel_Price         CPI  Unemployment  \
118    9.0           NaN        82.99       2.637  215.016648         6.384
11    18.0           0.0        52.02       2.878  132.763355         9.331
3     11.0           0.0        84.57         NaN  214.556497         7.346
54    10.0           0.0        86.87       3.666  130.719633         7.170
108   18.0           0.0        69.12       2.906  132.293936           NaN

       year  month   day
118  2010.0    6.0  18.0
11   2010.0   10.0  15.0
3       NaN    NaN   NaN
54   2012.0    7.0   6.0
108  2010.0    5.0  28.0
...Done.
  (0, 0)	1.2290638277821369
  (0, 1)	-1.4582304954209118
  (0, 2)	0.9667514709413112
  (0, 3)	-0.7618476721532947
  (0, 4)	-1.0760954651753933
  (0, 5)	-0.10134522606176094
  (0, 6)	0.21100432639720731
  (0, 14)	1.0
  (1, 0)	-0.5362568853900278
  (1, 1)	-0.9432885857676159
  (1, 2)	-1.1349501417076944
  (1, 3)	0.9838279099280447
  (1, 4)	-1.0760954651753933
  (1, 5)	1.2334455562150939
  (1, 6)	-0.1930465113846791
  (1, 23)	1.0
  (2, 0)	1.3191253946795218
  (2, 1)	-1.0988395028745035
  (2, 2)	0.954993870516385
  (2, 3)	-0.19200040036427246
  (2, 4)	-0.8250839959767649
  (2, 5)	0.16561293039360997
  (2, 6)	0.6689286092166784
  (2, 16)	1.0
  (3, 0)	1.4502276756060961
  (3, 1)	0.7404218906091351
  (3, 2)	-1.1871704551366444
  (3, 3)	-0.2962552026874201
  (3, 4)	1.4340192268103216
  (3, 5)	0.23235246950745275
  (3, 6)	-1.4051990247303383
  (3, 15)	1.0
  (4, 0)	0.43846007280319227
  (4, 1)	-0.8834613099572743
  (4, 2)	-1.1469445465106962
  (4, 3)	0.7706979219969738
  (4, 4)	-1.0760954651753933
  (4, 5)	-0.43504292163097463
  (4, 6)	1.5578404523368288
  (4, 23)	1.0

Performing preprocessings on test set...
     Store  Holiday_Flag  Temperature  Fuel_Price         CPI  Unemployment  \
28    17.0           0.0        45.22       2.915  126.562100         6.635
9      3.0           0.0        60.12       3.555  224.132020         6.833
58     6.0           0.0          NaN       2.640  212.894485         6.973
123    1.0           0.0          NaN       3.786  215.503788         7.682
46     5.0           0.0        82.46       2.640  211.927001         6.496

       year  month   day
28   2010.0    4.0  16.0
9       NaN    NaN   NaN
58   2010.0    7.0  30.0
123  2011.0    5.0  27.0
46   2010.0    7.0  30.0
...Done.
  (0, 0)	-0.9238636289990277
  (0, 1)	-0.8642311141610934
  (0, 2)	-1.2934019999030406
  (0, 3)	-0.6131661074765334
  (0, 4)	-1.0760954651753933
  (0, 5)	-0.7687406172001883
  (0, 6)	-0.05836289879071696
  (0, 22)	1.0
  (1, 0)	-0.07454885256166074
  (1, 1)	0.5032494757895679
  (1, 2)	1.1996636151602358
  (1, 3)	-0.4958794548629933
  (1, 4)	0.9319962884130645
  (1, 5)	0.3658315477351384
  (1, 6)	0.15713088135962267
  (1, 8)	1.0
  (2, 0)	-0.1623303797907577
  (2, 1)	-1.451820430155518
  (2, 2)	0.9125268328076066
  (2, 3)	-0.4129494984695796
  (2, 4)	-1.0760954651753933
  (2, 5)	0.23235246950745275
  (2, 6)	1.827207677524753
  (2, 11)	1.0
  (3, 0)	0.5393518281249464
  (3, 1)	0.9968245012248843
  (3, 2)	0.9791986522972788
  (3, 3)	0.007031494979918493
  (3, 4)	0.17896188081746411
  (3, 5)	-0.43504292163097463
  (3, 6)	1.4231568397428667
  (4, 0)	1.1988533021773176
  (4, 1)	-1.451820430155518
  (4, 2)	0.887806087971535
  (4, 3)	-0.6955037070385643
  (4, 4)	-1.0760954651753933
  (4, 5)	0.23235246950745275
  (4, 6)	1.827207677524753
  (4, 10)	1.0

/home/eugenie_laptop/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:241: UserWarning:

Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros

In [40]:
# Creation of the dictionnary keeping trace of the different models' results

dict_results = {}

# Baseline : linear regression model

In [41]:
# Model Linear Regression

regressor = LinearRegression()
regressor.fit(X_train, Y_train)

Y_train_pred = regressor.predict(X_train)
Y_test_pred = regressor.predict(X_test)
print("R2 score on training set : ", r2_score(Y_train, Y_train_pred))
print("R2 score on test set : ", r2_score(Y_test, Y_test_pred))

dict_results['baseline'] = [r2_score(Y_train, Y_train_pred), r2_score(Y_test, Y_test_pred)]

R2 score on training set :  0.9716833454556206
R2 score on test set :  0.930406401085691

In [28]:
# Cross-validation of the std on train

scores = cross_val_score(regressor, X_train, Y_train, cv=10)
avg = scores.mean()
std = scores.std()
print('Cross-validated accuracy : {}\nstandard deviation : {}'.format(avg, std))

# conclusion : on n'est pas en overfit, c'est dû à la petite taille du dataset

Cross-validated accuracy : 0.9328376213412997
standard deviation : 0.034958158516330065

In [29]:
# Analyzing the values of the model's coefficients

column_names = []
for name, pipeline, features_list in preprocessor.transformers_: 
    if name == 'num': 
        features = features_list 
    else: 
        features = pipeline.named_steps['encoder'].get_feature_names_out()
        features = list(features)
        features = np.char.replace(features, 'x0', features_list[0])
        features = np.char.replace(features, 'x1', features_list[1])
    column_names.extend(features) 
        
coefs = pd.DataFrame(index = column_names, data = regressor.coef_.transpose(), columns=["coefficients"])

feature_importance = coefs.sort_values(by = 'coefficients', key=abs)

fig = px.bar(feature_importance, orientation = 'h', height=700)
fig.update_layout(showlegend = False, 
                  margin = {'l': 120} 
                 )
fig.show()

# Regularized regression model

In [33]:
# Ridge

print("Grid search Ridge...")
model_ridge = Ridge()
params = {
    'alpha': [0, 0.01, 0.05, 0.1, 0.5, 1, 5] 
}
gridsearchR = GridSearchCV(model_ridge, param_grid = params, cv = 3) 
gridsearchR.fit(X_train, Y_train)
print("...Done.")
print("Best hyperparameters : ", gridsearchR.best_params_)
print("Best R2 score : ", gridsearchR.best_score_)

Grid search Ridge...
...Done.
Best hyperparameters :  {'alpha': 0.1}
Best R2 score :  0.9403342325650654

In [36]:
# Lasso

print("Grid search Lasso...")
model_lasso = Lasso()
params = {
    'alpha': [100, 1000, 1250, 1500, 1750, 2000] 
}
gridsearchL = GridSearchCV(model_lasso, param_grid = params, cv = 3) 
gridsearchL.fit(X_train, Y_train)
print("...Done.")
print("Best hyperparameters : ", gridsearchL.best_params_)
print("Best R2 score : ", gridsearchL.best_score_)

Grid search Lasso...
...Done.
Best hyperparameters :  {'alpha': 1500}
Best R2 score :  0.9441128718969934

In [37]:
# Features selected by Lasso(1500)

best_lasso = Lasso(alpha=1500)
best_lasso.fit(X_train, Y_train)

coefs_lasso = pd.DataFrame(index = column_names, data = best_lasso.coef_.transpose(), columns=["Lasso1500"])

feature_importance = coefs_lasso.sort_values(by = 'Lasso1500', key=abs)
#display(feature_importance)

fig = px.bar(feature_importance, orientation = 'h', height=700)
fig.update_layout(showlegend = False, 
                  margin = {'l': 120} 
                 )
fig.show()

### Conclusion

In [42]:
best_model_ridge = Ridge(alpha=0.1)
best_model_ridge.fit(X_train, Y_train)
Y_train_pred = best_model_ridge.predict(X_train)
Y_test_pred = best_model_ridge.predict(X_test)
dict_results['Ridge_01'] = [r2_score(Y_train, Y_train_pred), r2_score(Y_test, Y_test_pred)]

best_model_lasso = Lasso(alpha=1500)
best_model_lasso.fit(X_train, Y_train)
Y_train_pred = best_model_lasso.predict(X_train)
Y_test_pred = best_model_lasso.predict(X_test)
dict_results['Lasso_1500'] = [r2_score(Y_train, Y_train_pred), r2_score(Y_test, Y_test_pred)]

df_results = pd.DataFrame(dict_results, index=['R2_train', 'R2_test'])
display(df_results)

          baseline  Ridge_01  Lasso_1500
R2_train  0.971683  0.970679    0.968328
R2_test   0.930406  0.930049    0.940046

In [43]:
# Analyzing the values of Lasso's coefficients

scores = cross_val_score(best_model_lasso, X_train, Y_train, cv=10)
avg = scores.mean()
std = scores.std()
print('Cross-validated accuracy : {}\nstandard deviation : {}'.format(avg, std))

coefs = pd.DataFrame(index = column_names, data = best_model_lasso.coef_.transpose(), columns=["coefficients"])

feature_importance = coefs.sort_values(by = 'coefficients', key=abs)
feature_importance

fig = px.bar(feature_importance, orientation = 'h', height=700)
fig.update_layout(showlegend = False, 
                  margin = {'l': 120} 
                 )
fig.show()

Cross-validated accuracy : 0.9296196805454342
standard deviation : 0.04373996280847501

### Visualisation

In [44]:
# PCA: visualising the 3 better axes according to the target

from sklearn.decomposition import PCA

pca = PCA(n_components=3, random_state=0)
X_opt_train = pca.fit_transform(X_train.toarray())
print(f'Explained Variance ratio per PC: {pca.explained_variance_ratio_}')
print(f'Total explained variance ratio: {pca.explained_variance_ratio_.sum()}%')

X_opt_test = pca.transform(X_test.toarray())

best_model_lasso.fit(X_opt_train, Y_train)
print("score on test set: ", best_model_lasso.score(X_opt_test, Y_test))

df_pc = pd.DataFrame(X_opt_train)
df_test = pd.DataFrame(X_opt_test)
df_pc.columns = ["PC1", "PC2", "PC3"]
df_pc['Weekly_Sales'] = Y_train
fig = px.scatter_3d(df_pc, x="PC1", y="PC2", z="PC3", color="Weekly_Sales")
fig.show()

# components des 3 PC :
data = pd.DataFrame(pca.components_)
data.columns=column_names
print('PCA components for the first 3 axes:')
display(data)

#Associer les poids de PC1 aux noms des variables
pc1_components = pca.components_[0]
pc1_df = pd.DataFrame({
    'Variable': column_names,          # Noms des variables d'origine
    'PC1_Contribution': pc1_components  # Poids des variables dans PC1
})

#Trier par ordre décroissant d'importance
pc1_df = pc1_df.sort_values(by='PC1_Contribution', key=abs, ascending=False)
print("Weight of each feature in the first axis:")
display(pc1_df)

Explained Variance ratio per PC: [0.24557831 0.1906222  0.14746988]
Total explained variance ratio: 0.5836703976360653%
score on test set:  0.05983073842892517

PCA components for the first 3 axes:

,Temperature,Fuel_Price,CPI,Unemployment,year,month,day,Store_2.0,Store_3.0,Store_4.0,...,Store_13.0,Store_14.0,Store_15.0,Store_16.0,Store_17.0,Store_18.0,Store_19.0,Store_20.0,Holiday_Flag_0.4,Holiday_Flag_1.0
0,0.326107,-0.593783,0.163377,0.036152,-0.643849,0.256865,0.161934,0.002730,0.017477,0.008528,...,-0.022491,-0.018296,-0.016314,-0.013814,-0.003360,-0.009370,-0.012457,-0.003830,0.011953,0.002412
1,0.013880,0.086152,-0.647954,0.641607,-0.168976,0.236513,-0.218959,-0.026552,-0.041185,0.014750,...,0.012251,-0.000564,0.011428,-0.023130,0.032899,0.068447,0.024789,-0.015951,-0.005544,-0.000278
2,-0.651409,-0.406392,-0.076482,0.100839,-0.227615,-0.565626,-0.108817,0.010714,-0.033048,-0.019500,...,0.017245,0.033202,0.011537,0.004892,0.005133,-0.001545,0.023286,0.012217,0.007288,0.049424

Weight of each feature in the first axis:

            Variable  PC1_Contribution
4               year         -0.643849
1         Fuel_Price         -0.593783
0        Temperature          0.326107
5              month          0.256865
2                CPI          0.163377
6                day          0.161934
12         Store_7.0         -0.038925
3       Unemployment          0.036152
13         Store_8.0          0.031971
14         Store_9.0          0.030075
18        Store_13.0         -0.022491
16        Store_11.0          0.019443
19        Store_14.0         -0.018296
8          Store_3.0          0.017477
20        Store_15.0         -0.016314
11         Store_6.0          0.016053
21        Store_16.0         -0.013814
24        Store_19.0         -0.012457
26  Holiday_Flag_0.4          0.011953
23        Store_18.0         -0.009370
10         Store_5.0          0.008857
15        Store_10.0         -0.008627
9          Store_4.0          0.008528
25        Store_20.0         -0.003830
22        Store_17.0         -0.003360
7          Store_2.0          0.002730
27  Holiday_Flag_1.0          0.002412
17        Store_12.0         -0.001156

# Conclusion et Perspectives

Conclusion : les 3 modèles se valent, le meilleur sur le test est le Lasso (alpha = 1500) qui attribue un poids nul à l'année, deux des Store (#11 et #19) et l'absence de Holiday flag

Tests effectués non montrés dans ce Notebook :
- régression linéaire sans la colonne Store : donne un R2 de 0 -> les stores sont indispensables pour les prédictions
- faire l'imputation des dates directement sur la colonne Date, qui contient une information plus précise/complète que les colonnes year/month/day mais cela oblige à faire le KNN avant d'avoir créé X_train et X_test, donc pas de différenciation fit_transform et simple transform -> cela change un peu les figures (autant de 2011 que de 2010, mois un peu plus équilibrés) mais ne change presque pas les résultats des modèles

Perspectives :
- faire du feature engineering sur la colonne Store, pour ne pas avoir 20 colonnes après OHE, en faisant 2-4 catégories de stores (selon la target voire en combinaison avec d'autres features) 
- trouver les variables explicatives "cachées" entre les différents X, car au vu des pair-plots on voit de possibles clustering -> on peut créer des colonnes combinant variables quantitative et qualitative, et pour les duo de variables quantitatives on peut tester du feature engineering